theme: jekyll-theme-dinky
title: The title of the website shows here
description: A rapid description of the website content
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'sharks here !', 'pagename': 'page1'},
{'name': 'Go there', 'pagename': 'page2'},
{'name': 'Yet Another page', 'pagename': 'page3'},
]
